const {
  PUBLIC_URL,
  REACT_APP_ENDPOINT_AUTH,
  REACT_APP_ENDPOINT_GIPHY,
  REACT_APP_ENDPOINT_USERS,
  REACT_APP_ENDPOINT_WORDS,
  REACT_APP_GOOGLE_API_KEY,
  REACT_APP_GOOGLE_CLIENT_ID,
  REACT_APP_GOOGLE_CLIENT_SECRET,
  REACT_APP_GOOGLE_CSE_ID,
  REACT_APP_GIPHY_API_KEYS_00,
  REACT_APP_GIPHY_API_KEYS_01,
  REACT_APP_GIPHY_API_KEYS_02,
  REACT_APP_GIPHY_API_KEYS_03,
  REACT_APP_GIPHY_API_KEYS_04,
  REACT_APP_GIPHY_API_KEYS_05,
  REACT_APP_GIPHY_API_KEYS_06,
  REACT_APP_GIPHY_API_KEYS_07,
  REACT_APP_GIPHY_API_KEYS_08,
  REACT_APP_GIPHY_API_KEYS_09,
} = process.env;

const config = {
  publicUrl: PUBLIC_URL,
  auth: {
    google: {
      apiKey: REACT_APP_GOOGLE_API_KEY,
      clientId: REACT_APP_GOOGLE_CLIENT_ID,
      clientSecret: REACT_APP_GOOGLE_CLIENT_SECRET,
      cseId: REACT_APP_GOOGLE_CSE_ID,
    },
    giphy: {
      apiKeys: [
        REACT_APP_GIPHY_API_KEYS_00,
        REACT_APP_GIPHY_API_KEYS_01,
        REACT_APP_GIPHY_API_KEYS_02,
        REACT_APP_GIPHY_API_KEYS_03,
        REACT_APP_GIPHY_API_KEYS_04,
        REACT_APP_GIPHY_API_KEYS_05,
        REACT_APP_GIPHY_API_KEYS_06,
        REACT_APP_GIPHY_API_KEYS_07,
        REACT_APP_GIPHY_API_KEYS_08,
        REACT_APP_GIPHY_API_KEYS_09,
      ],
    },
  },
  endpoints: {
    auth: REACT_APP_ENDPOINT_AUTH,
    giphy: REACT_APP_ENDPOINT_GIPHY,
    users: REACT_APP_ENDPOINT_USERS,
    words: REACT_APP_ENDPOINT_WORDS,
  },
};

export default config;
